### ISSUE TITLE
[5주차] 구조 - 데코레이터 패턴

### ISSUE THREAD

**Issue by jun108059** [Nelmm/DesignPattern#30]
## 공부할 내용 📚

- [x] 데코레이터 패턴 1부 - 패턴 소개
- [x] 데코레이터 패턴 2부 - 패턴 적용하기
- [x] 데코레이터 패턴 3부 - 장점과 단점
- [x] 데코레이터 패턴 4부 - 자바와 스프링에서 찾아보는 패턴

**Comment by gowoonsori** [comment]
데코레이터 패턴은 데코레이터가 스택과 같이 쌓이면서 행위를 추가한다는 점에서 객체의 데이터를 바꾸거나 내부 프로퍼티가 수정되는 행위라고 한다면 데코레이터가 쌓이는 순서에 따라 결과물이 달라질 수 있을 것 같다. 
이러한 이유로 적용한다면 데코레이터를 감싸는 부분의 순서가 중요한 시스템에 대해서는 문서화를 잘해놓거나 이를 한번더 감싼 객체를 추가해야 할것 같고 비동기 환경에는 적용하기 힘들어 보인다.
